function_handlers = {
    # 綜合
    'AddExtParam':                  lambda indent, param: f"{indent}{param[1]}參數 + ( {param[2]} )",
    'SubExtParam':                  lambda indent, param: f"{indent}{param[1]}參數 - ( {param[2]} )",
    'AddMeleeAttackReflect':        lambda indent, param: f"{indent}反射 {param[0]}% 受到的近距離物理傷害",
    'AddReflectMagic':              lambda indent, param: f"{indent}有 {param[0]}% 的機率反射魔法",
    'AddEXPPercent_KillRace':       lambda indent, param: f"{indent}打倒 {param[0]}種族 取得的經驗值 + {param[1]}%",
    'SubEXPPercent_KillRace':       lambda indent, param: f"{indent}打倒 {param[0]}種族 取得的經驗值 - {param[1]}%",
    'AddReceiveItem_Equip':         lambda indent, param: f"{indent}掉寶率 + {param[0]}%",
    'AddNeverknockback':            lambda indent, param: f"{indent}{'會' if param[0] == '0' else '不會'} 被擊退",
    'AddSPconsumption':             lambda indent, param: f"{indent}施展技能的 SP 消耗 + {param[0]}%",
    'SubSPconsumption':             lambda indent, param: f"{indent}施展技能的 SP 消耗 - {param[0]}%",
    'AddCRIPercent_Race':           lambda indent, param: f"{indent}對 {param[1]}種族 的 CRI + {param[0]}‰ (此數值為千分比, 100‰ = 10%)",
    'AddGuideAttack':               lambda indent, param: f"{indent}誘導攻擊機率 + {param[0]}%",
    'AddHPdrain':                   lambda indent, param: f"{indent}物理攻擊有 {param[0]}% 的機率，吸收造成傷害的 {param[1]}% 到 HP 當中",
    'AddSPdrain':                   lambda indent, param: f"{indent}物理攻擊有 {param[0]}% 的機率，吸收造成傷害的 {param[1]}% 到 SP 當中",
    'AddHealModifyPercent':         lambda indent, param: f"{indent}接受到的恢復效果 + {param[0]}%",
    'SubHealModifyPercent':         lambda indent, param: f"{indent}接受到的恢復效果 - {param[0]}%",
    'AddHealValue':                 lambda indent, param: f"{indent}治癒系技能的恢復效果 + {param[0]}%",
    'AddSkillDelay':                lambda indent, param: f"{indent}技能 {param[0]} 的冷卻時間 + {param[1]} 毫秒",
    'SubSkillDelay':                lambda indent, param: f"{indent}技能 {param[0]} 的冷卻時間 - {param[1]} 毫秒",
    'AddSkillSP':                   lambda indent, param: f"{indent}技能 {param[0]} 的 SP 消耗 + {param[1]}",
    'SubSkillSP':                   lambda indent, param: f"{indent}技能 {param[0]} 的 SP 消耗 - {param[1]}",
    'AddSpecificSpellCastTime':     lambda indent, param: f"{indent}技能 {param[0]} 的特殊詠唱時間 -? {param[1]}% (通常為魔力增幅)",
    'SubSpecificSpellCastTime':     lambda indent, param: f"{indent}技能 {param[0]} 的變動詠唱時間 - {param[1]}% (通常為魔力增幅)",
    'AddSpellCastTime':             lambda indent, param: f"{indent}變動詠唱時間 + {param[0]}%",
    'SubSpellCastTime':             lambda indent, param: f"{indent}變動詠唱時間 - {param[0]}%",
    'AddSpellDelay':                lambda indent, param: f"{indent}共通技能後延遲 + {param[0]}%",
    'SubSpellDelay':                lambda indent, param: f"{indent}共通技能後延遲 - {param[0]}%",
    'Clairvoyance':                 lambda indent, param: f"{indent}{'無法' if param[0] == '0' else '可以'} 看見躲藏的目標",
    'EnableSkill':                  lambda indent, param: f"{indent}可以使用等級 {param[1]} 的技能 {param[0]}",
    'Magicimmune':                  lambda indent, param: f"{indent}{'無法' if param[0] == '0' else ''} 免疫魔法 (黃金蟲卡片)",
    'NoDispell':                    lambda indent, param: f"{indent}詠唱 {'會' if param[0] == '0' else '不會'} 被中斷",
    'NoJamstone':                   lambda indent, param: f"{indent}施展技能 {'會' if param[0] == '0' else '不會'} 消耗魔力礦石",
    'NoMadogearfuel':               lambda indent, param: f"{indent}施展技能 {'會' if param[0] == '0' else '不會'} 消耗魔導機甲燃料",
    'PerfectDamage':                lambda indent, param: f"{indent}{'保持' if param[0] == '0' else '刪除'} 武器體型懲罰",
    'Reincarnation':                lambda indent, param: f"{indent}復活時 HP 與 SP {'不會' if param[0] == '0' else '會'} 完全恢復",
    'SubReflectTolerace':           lambda indent, param: f"{indent}對 反擊傷害 的抗性 + {param[0]}%",
    'SubSFCTEquipAmount':           lambda indent, param: f"{indent}固定詠唱時間 - {param[1]} 毫秒",
    'SubSFCTEquipPermill':          lambda indent, param: f"{indent}固定詠唱時間 - {param[1]}%",
    
    # 傷害 (雜項)
    'AddDamage_SKID':               lambda indent, param: f"{indent}技能 {param[1]} 的傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",
    'AddBowAttackDamage':           lambda indent, param: f"{indent}弓的攻擊力 {'-' if param[0] == '0' else '+'} {param[1]}%",
    'AddDamage_CRI':                lambda indent, param: f"{indent}暴擊傷害 {'-' if param[0] == '0' else '+'} {param[1]}%",
    'AddDamage_HIT':                lambda indent, param: f"{indent}命中物理傷害 {'-' if param[0] == '0' else '+'} {param[1]}%",
    'AddMeleeAttackDamage':         lambda indent, param: f"{indent}對 近距離物理傷害 的抗性 + {param[1]}%" if param[0] == '0' else f"{indent}近距離物理傷害 + {param[1]}%",
    'SubMeleeAttackDamage':         lambda indent, param: f"{indent}對 近距離物理傷害 的抗性 + {param[1]}%" if param[0] == '0' else f"{indent}近距離物理傷害 - {param[1]}%",
    'AddRangeAttackDamage':         lambda indent, param: f"{indent}對 遠距離物理傷害 的抗性 + {param[1]}%" if param[0] == '0' else f"{indent}遠距離物理傷害 + {param[1]}%",
    'SubRangeAttackDamage':         lambda indent, param: f"{indent}對 遠距離物理傷害 的抗性 + {param[1]}%" if param[0] == '0' else f"{indent}遠距離物理傷害 - {param[1]}%",
    'AddSkillMDamage':              lambda indent, param: f"{indent}{param[0]}屬性 的魔法傷害 + {param[1]}%",
    'SubSkillMDamage':              lambda indent, param: f"{indent}{param[0]}屬性 的魔法傷害 - {param[1]}%",
    'SubDamage_CRI':                lambda indent, param: f"{indent}暴擊傷害 {'+' if param[0] == '0' else '-'} {param[1]}%",
    'SubDamage_SKID':               lambda indent, param: f"{indent}受到技能 {param[1]} 的傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",


    # 無視效果
    'SetIgnoreDEFClass':            lambda indent, param: f"{indent}無視 {param[0]}階級 100% 的 DEF",
    'SetIgnoreDefClass_Percent':    lambda indent, param: f"{indent}無視 {param[0]}階級 {param[1]}% 的 DEF",
    'SetIgnoreDEFRace':             lambda indent, param: f"{indent}無視 {param[0]}種族 100% 的 DEF",
    'SetIgnoreDefRace_Percent':     lambda indent, param: f"{indent}無視 {param[0]}種族 {param[1]}% 的 DEF",

    'SetIgnoreMdefClass':           lambda indent, param: f"{indent}無視 {param[0]}階級 {param[1]}% 的 MDEF",
    'SetIgnoreMdefRace':            lambda indent, param: f"{indent}無視 {param[0]}種族 {param[1]}% 的 MDEF",

    'AddIgnore_RES_RacePercent':    lambda indent, param: f"{indent}無視 {param[0]}種族 {param[1]}% 的 RES",
    'AddIgnore_MRES_RacePercent':   lambda indent, param: f"{indent}無視 {param[0]}種族 {param[1]}% 的 MRES",
    
    'SubIgnore_RES_RacePercent':    lambda indent, param: f"{indent}減少無視 {param[0]}種族 {param[1]}% 的 RES",
    'SubIgnore_MRES_RacePercent':   lambda indent, param: f"{indent}減少無視 {param[0]}種族 {param[1]}% 的 MRES",

    
    # 傷害 (體型, 屬性, 種族, 階級)
    # - 體型
    'AddDamage_Size':               lambda indent, param: f"{indent}對 {param[1]}體型 的物理傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",
    'AddMDamage_Size':              lambda indent, param: f"{indent}對 {param[1]}體型 的魔法傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",
    # - 屬性
    'AddDamage_Property':           lambda indent, param: f"{indent}{'來自' if param[0] == '0' else '對'} {param[1]}屬性 的物理傷害 + {param[2]}%",
    'AddMDamage_Property':          lambda indent, param: f"{indent}{'來自' if param[0] == '0' else '對'} {param[1]}屬性 的魔法傷害 + {param[2]}%",
    # - 種族
    'RaceAddDamage':                lambda indent, param: f"{indent}對 {param[0]}種族 的物理傷害 + {param[1]}%",
    'AddMdamage_Race':              lambda indent, param: f"{indent}對 {param[0]}種族 的魔法傷害 + {param[1]}%",
    'RaceSubDamage':                lambda indent, param: f"{indent}對 {param[0]}種族 的物理與魔法傷害 - {param[1]}%",
    # - 階級
    'ClassAddDamage':               lambda indent, param: f"{indent}{'來自' if param[1] == '0' else '對'} {param[0]}階級 的物理與魔法傷害 + {param[2]}%",
    'AddMdamage_Class':             lambda indent, param: f"{indent}對 {param[0]}階級 的魔法傷害 + {param[1]}%",
    'SubMdamage_Class':             lambda indent, param: f"{indent}對 {param[0]}階級 的魔法傷害 - {param[1]}%",

    
    # 抗性 (體型, 屬性, 種族, 階級)
    # - 體型
    'SubDamage_Size':               lambda indent, param: f"{indent}來自 {param[1]}體型 的物理傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",
    'SubMDamage_Size':              lambda indent, param: f"{indent}來自 {param[1]}體型 的魔法傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",
    # - 屬性
    'AddAttrTolerace':              lambda indent, param: f"{indent}對 {param[0]}屬性 的抗性 + {param[1]}%",
    'SubAttrTolerace':              lambda indent, param: f"{indent}對 {param[0]}屬性 的抗性 - {param[1]}%",
    'SubDamage_Property':           lambda indent, param: f"{indent}來自 {param[1]}屬性 敵人的物理傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",
    'SubMDamage_Property':          lambda indent, param: f"{indent}來自 {param[1]}屬性 敵人的魔法傷害 {'-' if param[0] == '0' else '+'} {param[2]}%",

    # - 種族
    'AddRaceTolerace':              lambda indent, param: f"{indent}對 {param[0]}種族 的抗性 + {param[1]}%",
    'SubRaceTolerace':              lambda indent, param: f"{indent}對 {param[0]}種族 的抗性 - {param[1]}%",
    'RaceAddDamageSelf':            lambda indent, param: f"{indent}來自 {param[0]}種族 的傷害 + {param[1]}%",
    # - 階級
    'ClassSubDamage':               lambda indent, param: f"{indent}{'來自' if param[1] == '0' else '對'} {param[0]}階級 的物理與魔法傷害 - {param[2]}% (有誤的機會較高)",
}

keep_word_table = {
    'local': '宣告參數',
    'GetSkillLevel': '指定技能的習得等級',
    'GetRefineLevel(2)': '鎧甲的精煉值',
    'GetRefineLevel(3)': '盾牌的精煉值',
    'GetRefineLevel(4)': '武器的精煉值',
    'GetRefineLevel(5)': '披肩的精煉值',
    'GetRefineLevel(6)': '鞋子的精煉值',
    'GetRefineLevel(10)': '頭飾的精煉值',

    'GetRefineLevel(30)': '影子鎧甲的精煉值',
    'GetRefineLevel(31)': '影子手套的精煉值',
    'GetRefineLevel(32)': '影子神盾的精煉值',
    'GetRefineLevel(33)': '鞋子戰靴的精煉值',
    'GetRefineLevel(34)': '影子耳環的精煉值',
    'GetRefineLevel(35)': '影子墜子的精煉值',

    'get(19) == 4054': 'get(19) == 盧恩騎士',
    'get(19) == 4055': 'get(19) == 咒術士',
    'get(19) == 4056': 'get(19) == 遊俠',
    'get(19) == 4057': 'get(19) == 大主教',
    'get(19) == 4058': 'get(19) == 機械工匠',
    'get(19) == 4059': 'get(19) == 十字斬首者',
    'get(19) == 4060': 'get(19) == 盧恩騎士 H',
    'get(19) == 4061': 'get(19) == 咒術士 H',
    'get(19) == 4062': 'get(19) == 遊俠 H',
    'get(19) == 4063': 'get(19) == 大主教 H',
    'get(19) == 4064': 'get(19) == 機械工匠 H',
    'get(19) == 4065': 'get(19) == 十字斬首者 H',

    'get(19) == 4066': 'get(19) == 皇家禁衛隊',
    'get(19) == 4067': 'get(19) == 妖術師',
    'get(19) == 4068': 'get(19) == 宮廷樂師',
    'get(19) == 4069': 'get(19) == 浪跡舞者',
    'get(19) == 4070': 'get(19) == 修羅',
    'get(19) == 4071': 'get(19) == 基因學者',
    'get(19) == 4072': 'get(19) == 魅影追蹤者',
    'get(19) == 4073': 'get(19) == 皇家禁衛隊 H',
    'get(19) == 4074': 'get(19) == 妖術師 H',
    'get(19) == 4075': 'get(19) == 宮廷樂師 H',
    'get(19) == 4076': 'get(19) == 浪跡舞者 H',
    'get(19) == 4077': 'get(19) == 修羅 H',
    'get(19) == 4078': 'get(19) == 基因學者 H',
    'get(19) == 4079': 'get(19) == 魅影追蹤者 H',

    'get(19) == 4096': 'get(19) == 小孩盧恩騎士',
    'get(19) == 4097': 'get(19) == 小孩咒術士',
    'get(19) == 4098': 'get(19) == 小孩遊俠',
    'get(19) == 4099': 'get(19) == 小孩大主教',
    'get(19) == 4100': 'get(19) == 小孩機械工匠',
    'get(19) == 4101': 'get(19) == 小孩十字斬首者',

    'get(19) == 4102': 'get(19) == 小孩皇家禁衛隊',
    'get(19) == 4103': 'get(19) == 小孩妖術師',
    'get(19) == 4104': 'get(19) == 小孩宮廷樂師',
    'get(19) == 4105': 'get(19) == 小孩浪跡舞者',
    'get(19) == 4106': 'get(19) == 小孩修羅',
    'get(19) == 4107': 'get(19) == 小孩基因學者',
    'get(19) == 4108': 'get(19) == 小孩魅影追蹤者',

    'get(19) == 4190': 'get(19) == 超級初學者 等級突破',
    'get(19) == 4211': 'get(19) == 日影忍者',
    'get(19) == 4212': 'get(19) == 月影忍者',
    'get(19) == 4215': 'get(19) == 叛亂者',
    'get(19) == 4218': 'get(19) == 喵族(召喚師)',
    'get(19) == 4239': 'get(19) == 拳皇',
    'get(19) == 4240': 'get(19) == 獵靈士',

    'get(19) == 4191': 'get(19) == 小孩超級初學者 等級突破',
    'get(19) == 4223': 'get(19) == 小孩日影忍者',
    'get(19) == 4224': 'get(19) == 小孩月影忍者',
    'get(19) == 4229': 'get(19) == 小孩叛亂者',
    'get(19) == 4220': 'get(19) == 小孩喵族(召喚師)',
    'get(19) == 4241': 'get(19) == 小孩拳皇',
    'get(19) == 4242': 'get(19) == 小孩獵靈士',

    'get(19) == 4252': 'get(19) == 盧恩龍爵',
    'get(19) == 4253': 'get(19) == 機甲神匠',
    'get(19) == 4254': 'get(19) == 十字影武',
    'get(19) == 4255': 'get(19) == 禁咒魔導士',
    'get(19) == 4256': 'get(19) == 樞機主教',
    'get(19) == 4257': 'get(19) == 風鷹狩獵者',
    'get(19) == 4258': 'get(19) == 帝國聖衛軍',
    'get(19) == 4259': 'get(19) == 生命締造者',
    'get(19) == 4260': 'get(19) == 深淵追跡者',
    'get(19) == 4261': 'get(19) == 元素支配者',
    'get(19) == 4262': 'get(19) == 聖裁者',
    'get(19) == 4263': 'get(19) == 天籟頌者',
    'get(19) == 4264': 'get(19) == 樂之舞靈',
    'get(19) == 4302': 'get(19) == 天帝',
    'get(19) == 4303': 'get(19) == 契靈士',
    'get(19) == 4304': 'get(19) == 流浪忍者',
    'get(19) == 4305': 'get(19) == 疾風忍者',
    'get(19) == 4306': 'get(19) == 夜行使',
    'get(19) == 4307': 'get(19) == 終極初學者',
    'get(19) == 4308': 'get(19) == 魂靈師',
}

ext_param_table = {
    '103參數': 'STR', '104參數': 'AGI', '105參數': 'VIT', '106參數': 'INT', '107參數': 'DEX', '108參數': 'LUK',
    '109參數': 'MHP', '110參數': 'MSP', '111參數': 'MHP %', '112參數': 'MSP %',
    '113參數': 'HP 自然恢復力', '114參數': 'SP 自然恢復力',
    '140參數': 'MATK %',
    '140參數': 'ASPD %',
    '200參數': 'MATK',
    '207參數': 'ATK %',
    '234參數': 'POW', '235參數': 'STA', '236參數': 'WIS', '237參數': 'SPL', '238參數': 'CON', '239參數': 'CRT',
    '242參數': 'P.ATK', '243參數': 'S.MATK',
    '244參數': 'RES', '245參數': 'MRES',
    '253參數': 'C.RATE',
    '254參數': 'H.PLUS',
    '41參數': 'ATK',
    '45參數': 'DEF', '47參數': 'MDEF',
    '49參數': 'HIT',
    '50參數': 'FLEE',
    '51參數': '完全迴避 (此數值需再乘 0.1)',
    '52參數': 'CRI (此數值需再乘 0.1)',
    '54參數': 'ASPD',
}

get_table = {
    'get(255)': '裝備者的純粹 POW',
    'get(256)': '裝備者的純粹 STA',
    'get(257)': '裝備者的純粹 WIS',
    'get(258)': '裝備者的純粹 SPL',
    'get(259)': '裝備者的純粹 CON',
    'get(260)': '裝備者的純粹 CRT',
    'get(11)': '裝備者的基本等級',
    'get(19)': '裝備者的職業',
    'get(32)': '裝備者的純粹 STR',
    'get(33)': '裝備者的純粹 AGI',
    'get(34)': '裝備者的純粹 VIT',
    'get(35)': '裝備者的純粹 INT',
    'get(36)': '裝備者的純粹 DEX',
    'get(37)': '裝備者的純粹 LUK',
    'get(55)': '裝備者的職業等級',
}

size_table = {
    '0體型': '小型體型',
    '1體型': '中型體型',
    '2體型': '大型體型',
}

class_table = {
    '0階級': '一般階級',
    '1階級': 'Boss 階級',
    '2階級': '護衛階級',
}

element_table = {
    '999屬性': '未知屬性(NeverUse)',
    '0屬性': '無屬性',
    '1屬性': '水屬性',
    '2屬性': '地屬性',
    '3屬性': '火屬性',
    '4屬性': '風屬性',
    '5屬性': '毒屬性',
    '6屬性': '聖屬性',
    '7屬性': '暗屬性',
    '8屬性': '念屬性',
    '9屬性': '不死屬性',
    '10屬性': '所有屬性',
}

race_table = {
    '9999種族': '所有種族',
    '0種族': '無形種族',
    '1種族': '不死種族',
    '2種族': '動物種族',
    '3種族': '植物種族',
    '4種族': '昆蟲種族',
    '5種族': '魚貝種族',
    '6種族': '惡魔種族',
    '7種族': '人形種族',
    '8種族': '天使種族',
    '9種族': '龍族種族',
    '10種族': '人形玩家種族',
    '11種族': '動物玩家種族',
}